// auto generated by go tool dist

package sys

const DefaultGoroot = `C:\Users\ADAMTA~1\AppData\Local\Temp\2\appengine\go_appengine\goroot`
const TheVersion = `go1.6.1 (appengine-1.9.38)`
const Goexperiment = ``
const StackGuardMultiplier = 1

